"""Shared option definitions and the error type raised on bad user input.

Every user-facing option is described exactly once, in ``OPTION_DOCS``. The
``click`` CLI in `prot_struct_viz.cli` and the ``render`` function in
`prot_struct_viz` both read from here, so the two surfaces cannot disagree
about what an option means.
"""

from __future__ import annotations

import dataclasses
import pathlib

#: Default color for structure residues that have no CSV row.
DEFAULT_COLOR = "#d9d9d9"

#: Representation applied to the whole displayed polymer unless overridden.
DEFAULT_REPRESENTATION = "cartoon"

#: What to do when the CSV and the structure disagree about the residue set.
MISMATCH_MODES = (
    "error-any",
    "error-extra-in-pdb",
    "error-extra-in-csv",
    "report",
)

#: Representations a user may name, mapped to the MolViewSpec representation type.
#: This is the single source of allowed values for the CSV ``representation``
#: column, ``--default-representation``, and ``--chain-representation``.
#:
#: Mol* itself also draws ``backbone``, ``line``, and ``putty``, but the
#: molviewspec Python package we build the state with does not accept them yet,
#: so naming one would produce a state that fails validation. They are left out
#: rather than offered and silently broken.
REPRESENTATIONS = {
    "cartoon": "cartoon",
    "ball-and-stick": "ball_and_stick",
    "spacefill": "spacefill",
    "surface": "surface",
    "carbohydrate": "carbohydrate",
}

#: Color of persistent on-structure label text when the CSV does not give one.
DEFAULT_LABEL_COLOR = "#000000"

#: Height of persistent label text, in Angstroms of world space, when the CSV does
#: not give one. Mol*'s own default of 1 is about a bond length and reads very small
#: beside a residue.
DEFAULT_LABEL_SIZE = 2.0

#: Representation given to a CSV-named non-polymer residue that does not specify
#: one of its own. The global/per-chain base is a polymer representation
#: (``cartoon`` by default) and would draw nothing for a ligand or ion.
HETERO_CSV_REPRESENTATION = "ball-and-stick"

OPTION_DOCS = {
    "structure": "PDB ID to fetch from RCSB, or path to a local .cif/.pdb file.",
    "csv": "Residue color/label/representation table. See the CSV schema docs.",
    "out": "Output HTML file. Must end in '.html'.",
    "assembly": (
        "'au' for the deposited asymmetric unit, or an assembly id (e.g. '1'). "
        "Assemblies are generated by Mol* in the browser, not expanded here."
    ),
    "chains": "Comma-separated deposited chain IDs to display. Default: all chains.",
    "on_mismatch": (
        "What to do when the CSV residue set and the structure's addressable "
        "residue set differ. A report file is written in every mode."
    ),
    "default_color": "Color for structure residues that have no CSV row.",
    "default_representation": "Base representation applied to the whole displayed polymer.",
    "chain_representation": (
        "Optional CSV with columns 'chain,representation' overriding the base "
        "representation for those chains."
    ),
    "waters": "Show or hide waters. Waters are not individually addressable from the CSV.",
    "ligands": "Show or hide ligands not named in the CSV (element-colored ball-and-stick).",
    "glycans": (
        "Draw glycans not named in the CSV as 3D-SNFG symbols, or hide them. A "
        "glycan named in the CSV is never drawn as an SNFG symbol."
    ),
    "ions": "Show or hide ions not named in the CSV (element-colored spacefill).",
    "title_md": "Optional Markdown file rendered into a header block above the viewer.",
    "cache_dir": "Directory for structures downloaded from RCSB.",
}

#: Where structures fetched from RCSB are cached.
DEFAULT_CACHE_DIR = pathlib.Path.home() / ".cache" / "prot-struct-viz"


class InputError(Exception):
    """Raised on invalid user input (bad CSV, bad structure, failed validation).

    The CLI catches this, writes the report, and exits non-zero. It never
    carries a traceback to the user: the message is the whole story.
    """


@dataclasses.dataclass(frozen=True)
class ViewConfig:
    """Everything that controls a rendered view, shared by the CLI and ``render``.

    Field meanings are in `OPTION_DOCS`, keyed by field name.
    """

    assembly: str = "au"
    chains: tuple[str, ...] | None = None
    on_mismatch: str = "report"
    default_color: str = DEFAULT_COLOR
    default_representation: str = DEFAULT_REPRESENTATION
    waters: str = "hide"
    ligands: str = "show"
    glycans: str = "snfg"
    ions: str = "show"

    def __post_init__(self):
        if self.on_mismatch not in MISMATCH_MODES:
            raise InputError(
                f"on_mismatch must be one of {list(MISMATCH_MODES)}, got "
                f"{self.on_mismatch!r}"
            )
        for name, allowed in [
            ("waters", ("hide", "show")),
            ("ligands", ("show", "hide")),
            ("glycans", ("snfg", "hide")),
            ("ions", ("show", "hide")),
        ]:
            value = getattr(self, name)
            if value not in allowed:
                raise InputError(
                    f"{name} must be one of {list(allowed)}, got {value!r}"
                )
        if self.default_representation not in REPRESENTATIONS:
            raise InputError(
                f"default_representation must be one of {sorted(REPRESENTATIONS)}, "
                f"got {self.default_representation!r}"
            )
