"""Fetch, load, and describe the deposited coordinates.

Everything here works on the **deposited** (asymmetric-unit) model. Biological
assemblies are generated by Mol* in the browser from an assembly id, so symmetry
copies never introduce new residue numbers and validation is independent of the
assembly flag.
"""

from __future__ import annotations

import gzip
import pathlib
import re
import urllib.error
import urllib.request
from typing import Literal

import gemmi

from ._config import InputError
from .residues import ResidueKey

#: How a residue is classified for heteroatom handling and the mismatch report.
ResidueClass = Literal["polymer", "ligand", "glycan", "ion", "water"]

#: Residue classes a CSV row may target: everything except water.
ADDRESSABLE_CLASSES = ("polymer", "ligand", "glycan", "ion")

#: A classic 4-character PDB ID, or an extended ``pdb_XXXXXXXX`` one.
PDB_ID_RE = re.compile(r"^(?:[0-9][A-Za-z0-9]{3}|pdb_[A-Za-z0-9]{8})$")

RCSB_URL = "https://files.rcsb.org/download/{pdb_id}.cif"

_SUFFIX_FORMATS = {
    ".cif": "mmcif",
    ".mmcif": "mmcif",
    ".pdb": "pdb",
    ".ent": "pdb",
}

#: gemmi residue kinds that mean "a sugar", used when the file carries no
#: ``branched`` entity (as PDB-format files do not).
_SUGAR_KINDS = (gemmi.ResidueKind.PYR, gemmi.ResidueKind.KET)


def _read_text(path: pathlib.Path) -> str:
    """Read a coordinate file, transparently decompressing ``.gz``."""
    if path.suffix == ".gz":
        with gzip.open(path, "rt", encoding="utf-8") as f:
            return f.read()
    return path.read_text(encoding="utf-8")


def _format_from_path(path: pathlib.Path) -> str:
    """The coordinate format implied by a filename suffix."""
    suffixes = [s.lower() for s in path.suffixes]
    if suffixes and suffixes[-1] == ".gz":
        suffixes = suffixes[:-1]
    if not suffixes or suffixes[-1] not in _SUFFIX_FORMATS:
        raise InputError(
            f"cannot tell the format of {path} from its name: expected one of "
            f"{sorted(_SUFFIX_FORMATS)} (optionally with a .gz suffix)"
        )
    return _SUFFIX_FORMATS[suffixes[-1]]


def resolve_structure(source: str) -> tuple[str, str]:
    """Resolve ``source`` to coordinate text plus its format.

    An existing path is read as-is. Otherwise a PDB ID is downloaded as mmCIF
    from RCSB. Anything that is neither is an error: the source is never
    guessed at.

    Downloads are not cached. Only the coordinate *text* is used downstream, so
    a cache would buy one HTTP request at the cost of a stale-file failure mode;
    pass a local file to ``source`` to render the same coordinates repeatedly.

    Parameters
    ----------
    source
        A PDB ID (e.g. ``1F8B``) or a path to a local ``.cif``/``.pdb`` file.

    Returns
    -------
    tuple
        ``(coordinate_text, format)`` where format is ``"mmcif"`` or ``"pdb"``.
        The text is embedded verbatim in the output HTML.
    """
    path = pathlib.Path(source)
    if path.is_file():
        return _read_text(path), _format_from_path(path)

    if not PDB_ID_RE.match(source):
        raise InputError(
            f"--structure {source!r} is neither an existing file nor a PDB ID "
            "(a 4-character id like '1F8B', or 'pdb_' plus 8 characters)"
        )

    url = RCSB_URL.format(pdb_id=source.lower())
    try:
        with urllib.request.urlopen(url) as response:
            text = response.read().decode("utf-8")
    except urllib.error.URLError as err:
        raise InputError(f"could not download {url}: {err}") from err
    return text, "mmcif"


def load_structure(coordinate_text: str, fmt: str) -> gemmi.Structure:
    """Parse coordinate text into a gemmi structure with entity info set up.

    The original text is what gets embedded in the HTML; this parsed copy is
    only used to enumerate and classify residues.
    """
    if fmt == "mmcif":
        block = gemmi.cif.read_string(coordinate_text).sole_block()
        structure = gemmi.make_structure_from_block(block)
    elif fmt == "pdb":
        structure = gemmi.read_pdb_string(coordinate_text)
    else:
        raise InputError(f"unknown coordinate format {fmt!r}")
    if len(structure) == 0:
        raise InputError("structure contains no models")
    structure.setup_entities()
    # mmCIF parsing yields one chain per subchain, so an author chain holding both
    # polymer and heteroatoms arrives as several same-named chains. Merge them so
    # there is exactly one chain object per author chain ID.
    structure.merge_chain_parts()
    return structure


def _entity_types(structure: gemmi.Structure) -> dict[str, gemmi.EntityType]:
    """Map subchain (label_asym_id) -> entity type."""
    return {
        subchain: entity.entity_type
        for entity in structure.entities
        for subchain in entity.subchains
    }


def _classify(residue: gemmi.Residue, entity_type: gemmi.EntityType) -> ResidueClass:
    """Classify one residue for heteroatom handling.

    Entity type decides where it can: mmCIF marks glycans as ``branched`` and
    waters as ``water``. For anything else -- including PDB-format files, which
    have no entities -- fall back to the chemical component: a pyranose or
    ketose is a glycan, and a residue modeled as a single heavy atom whose name
    is the residue name (``ZN``, ``CA``) is a monatomic ion.
    """
    if entity_type == gemmi.EntityType.Water or residue.name == "HOH":
        return "water"
    if entity_type == gemmi.EntityType.Polymer:
        return "polymer"
    if entity_type == gemmi.EntityType.Branched:
        return "glycan"

    info = gemmi.find_tabulated_residue(residue.name)
    if info is not None:
        if info.is_water():
            return "water"
        if info.kind in _SUGAR_KINDS:
            return "glycan"
    heavy = [atom for atom in residue if not atom.element.is_hydrogen]
    if (
        len(heavy) == 1
        and heavy[0].name.strip().upper() == residue.name.strip().upper()
    ):
        return "ion"
    return "ligand"


def residue_key(chain: gemmi.Chain, residue: gemmi.Residue) -> ResidueKey:
    """The ``(chain, residue)`` key for a residue, in author numbering."""
    return (chain.name, f"{residue.seqid.num}{residue.seqid.icode.strip()}")


def get_deposited_residues(
    structure: gemmi.Structure, chains: list[str] | None = None
) -> dict[ResidueKey, ResidueClass]:
    """Every ``(chain, residue)`` key in the deposited model, with its class.

    Parameters
    ----------
    structure
        A structure from `load_structure`.
    chains
        If given, restrict to these deposited (author) chain IDs.

    Returns
    -------
    dict
        ``(chain, residue)`` -> residue class, in author numbering with
        insertion codes preserved in the residue string.
    """
    wanted = set(chains) if chains is not None else None
    if wanted is not None:
        present = {chain.name for chain in structure[0]}
        unknown = sorted(wanted - present)
        if unknown:
            raise InputError(
                f"chains names chain(s) not in the structure: {unknown}; "
                f"available chains are {sorted(present)}"
            )

    entity_types = _entity_types(structure)
    deposited: dict[ResidueKey, ResidueClass] = {}
    for chain in structure[0]:
        if wanted is not None and chain.name not in wanted:
            continue
        for residue in chain:
            entity_type = entity_types.get(residue.subchain, gemmi.EntityType.Unknown)
            deposited[residue_key(chain, residue)] = _classify(residue, entity_type)
    if not deposited:
        raise InputError("structure contains no residues")
    return deposited


def addressable_residues(
    deposited: dict[ResidueKey, ResidueClass],
) -> set[ResidueKey]:
    """The residues a CSV row may target: everything except water."""
    return {key for key, cls in deposited.items() if cls in ADDRESSABLE_CLASSES}


def residue_counts(
    structure: gemmi.Structure, chains: list[str] | None = None
) -> dict[str, int]:
    """Per-chain residue counts, for the progress log."""
    wanted = set(chains) if chains is not None else None
    counts: dict[str, int] = {}
    for chain in structure[0]:
        if wanted is None or chain.name in wanted:
            counts[chain.name] = counts.get(chain.name, 0) + len(chain)
    return counts


def get_assembly_chains(
    structure: gemmi.Structure, assembly_id: str
) -> set[str] | None:
    """Deposited author chain IDs used by an assembly (``None`` for ``"au"``).

    Assembly generators name subchains (``label_asym_id``), so they are mapped
    back to the author chain IDs the CSV uses.
    """
    if assembly_id == "au":
        return None

    available = [assembly.name for assembly in structure.assemblies]
    matching = [a for a in structure.assemblies if a.name == assembly_id]
    if not matching:
        raise InputError(
            f"assembly {assembly_id!r} is not defined by this structure; "
            f"available assemblies are {available or '(none)'} (or 'au' for the "
            "deposited asymmetric unit)"
        )

    subchain_to_chain: dict[str, str] = {}
    for chain in structure[0]:
        for residue in chain:
            subchain_to_chain.setdefault(residue.subchain, chain.name)

    chains: set[str] = set()
    for generator in matching[0].generators:
        chains.update(generator.chains)
        for subchain in generator.subchains:
            if subchain in subchain_to_chain:
                chains.add(subchain_to_chain[subchain])
    return chains


def assembly_names(structure: gemmi.Structure) -> list[str]:
    """Assembly ids defined by the structure, for the progress log."""
    return [assembly.name for assembly in structure.assemblies]


def residue_centroids(
    structure: gemmi.Structure, chains: list[str] | None = None
) -> dict[ResidueKey, tuple[float, float, float]]:
    """Centroid of each residue's heavy atoms, for anchoring 3D labels.

    Labels are drawn as MolViewSpec primitives at explicit coordinates rather than
    through ``label_from_uri``, which derives one position from the boundary sphere
    of every matching atom -- across every symmetry copy -- and so puts a label in
    the middle of an assembly. See CLAUDE.md.

    Parameters
    ----------
    structure
        A structure from `load_structure`.
    chains
        If given, restrict to these deposited (author) chain IDs.

    Returns
    -------
    dict
        ``(chain, residue)`` -> ``(x, y, z)``. Residues with no heavy atoms are
        omitted.
    """
    wanted = set(chains) if chains is not None else None
    centroids: dict[ResidueKey, tuple[float, float, float]] = {}
    for chain in structure[0]:
        if wanted is not None and chain.name not in wanted:
            continue
        for residue in chain:
            heavy = [atom for atom in residue if not atom.element.is_hydrogen]
            if not heavy:
                continue
            n = len(heavy)
            centroids[residue_key(chain, residue)] = (
                sum(atom.pos.x for atom in heavy) / n,
                sum(atom.pos.y for atom in heavy) / n,
                sum(atom.pos.z for atom in heavy) / n,
            )
    return centroids


def _transform_to_mat4(transform: gemmi.Transform) -> list[float]:
    """A gemmi transform as a 4x4 column-major matrix (MVS uses j * 4 + i indexing)."""
    rotation = transform.mat.tolist()
    translation = list(transform.vec.tolist())
    return [
        rotation[0][0],
        rotation[1][0],
        rotation[2][0],
        0.0,
        rotation[0][1],
        rotation[1][1],
        rotation[2][1],
        0.0,
        rotation[0][2],
        rotation[1][2],
        rotation[2][2],
        0.0,
        translation[0],
        translation[1],
        translation[2],
        1.0,
    ]


def assembly_instance_transforms(
    structure: gemmi.Structure, assembly_id: str
) -> list[tuple[set[str], list[list[float]]]]:
    """The transforms an assembly applies, grouped by the chains they apply to.

    An assembly may have several generators, each applying its own operators to its
    own subchains, so the transforms are returned per generator rather than as one
    flat list -- replicating a label by an operator that does not apply to its chain
    would put the label nowhere near the structure.

    Returns
    -------
    list of tuple
        ``(author chain IDs, list of 4x4 column-major matrices)``, one entry per
        generator. Empty for ``"au"``, which needs no transform at all.
    """
    if assembly_id == "au":
        return []

    matching = [a for a in structure.assemblies if a.name == assembly_id]
    if not matching:
        raise InputError(
            f"assembly {assembly_id!r} is not defined by this structure; "
            f"available assemblies are {assembly_names(structure) or '(none)'}"
        )

    subchain_to_chain: dict[str, str] = {}
    for chain in structure[0]:
        for residue in chain:
            subchain_to_chain.setdefault(residue.subchain, chain.name)

    groups = []
    for generator in matching[0].generators:
        chains = set(generator.chains)
        for subchain in generator.subchains:
            if subchain in subchain_to_chain:
                chains.add(subchain_to_chain[subchain])
        groups.append(
            (chains, [_transform_to_mat4(op.transform) for op in generator.operators])
        )
    return groups
